### ISSUE TITLE
Unable to get X11 socket forwarding working

### ISSUE THREAD

**Issue by pinkgladiator** [koenrh/docker-burp-suite-pro#5]
Hey @koenrh!

Thanks so much for sharing your Burp Suite Pro container. I first had a problem getting it to work because my PortSwigger-generated password started in a `@` character, throwing off `curl` (duh!). After changing my password, I'm now running into a problem with forwarding the X11 socket to XQuartz. In your [setup instructions](https://github.com/koenrh/docker-burp-suite-pro#setup) you say to run `socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"`. I'm taking that as needing to run this from an XQuartz terminal as that's the only place that would actually have the `DISPLAY` environment variable set (it's set to `:0` here). But then how is this `socat` invocation supposed to work? If I do this, `socat` tries to open a UNIX domain socket with the file name `":0"`, which of course does not exist:

```
bash-3.2$ socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"
2019/04/18 21:03:17 socat[66234] E connect(5, LEN=4 AF=1 ":0", 4): No such file or directory
2019/04/18 21:03:17 socat[66235] E connect(5, LEN=4 AF=1 ":0", 4): No such file or directory
2019/04/18 21:13:38 socat[68506] E connect(5, LEN=4 AF=1 ":0", 4): No such file or directory
```

What am I missing?

**Comment by koenrh** [comment]
Hi YanYan,

> In your setup instructions you say to run `socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"`. I'm taking that as needing to run this from an XQuartz terminal as that's the only place that would actually have the DISPLAY environment variable set (it's set to :0 here).

You need to run `socat` on your host.

It basically opens a bidirectional connection between the Docker container and the X server on your host, i.e. a network socket (with TCP listener on X server default port 6000) and X server on your host (unix socket).

Let me know if that works. I will update the README to clarify that.

**Comment by pinkgladiator** [comment]
My mistake, I forgot to restart the Mac after install XQaurtz. I have another question: what is the purpose of $HOME"/src/github.com/koenrh/burp/java:/home/burp/.java"? Is that to retain the license activation information?

**Comment by koenrh** [comment]
Correct. You don't want to activate your license too often, because there is some kind of cap in place on the number of activations.

**Comment by pinkgladiator** [comment]
I got it to work. Many thanks.
